#!/usr/bin/perl

# Copyright 2019 ByWater Solutions
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <https://www.gnu.org/licenses>.

use Modern::Perl;

use CGI;
use JSON qw(to_json);
use Try::Tiny;

use C4::Auth qw(check_cookie_auth haspermission);
use C4::Context;
use C4::Output qw( output_with_http_headers );

use Koha::AuthorisedValues;
use Koha::DateUtils qw( dt_from_string output_pref );
use Koha::Patron::Disclosure;
use Koha::Patrons;

my $input = CGI->new;

my ( $auth_status, $session ) = check_cookie_auth( $input->cookie('CGISESSID') );
if ( $auth_status ne 'ok' ) {
    print CGI::header( '-status' => '401' );
    exit 0;
}

my $userid = $session->param('id');

unless ( haspermission( $userid, { circulate => 'circulate_remaining_permissions' } )
    || haspermission( $userid, { borrowers => 'edit_borrowers' } ) )
{
    exit 0;
}

my @sort_columns = qw/title notes created_on updated_on/;

my $borrowernumber;
my $offset           = $input->param('iDisplayStart');
my $results_per_page = $input->param('iDisplayLength') || -1;

my $disclosure_enabled = Koha::Patron::Disclosure->enabled;
my @disclosure_patron_ids;
if ($disclosure_enabled) {
    my @raw_borrowernumbers = $input->multi_param('borrowernumber');
    my $resolved_id;
    try {
        $resolved_id = Koha::Patron::Disclosure->resolve_single_patron_id( \@raw_borrowernumbers );
    } catch {
        my $is_input_error = ref($_) eq 'Koha::Exceptions::BadParameter'
            && ( $_->parameter // q{} ) eq 'patron_disclosure_subjects';
        my ( $status, $error_code ) =
            $is_input_error
            ? ( '400 Bad Request', 'patron_disclosure_invalid_subjects' )
            : ( '503 Service Unavailable', 'patron_disclosure_subject_resolution_unavailable' );
        my $error = $status =~ /\A400/ ? 'Invalid request' : 'Service unavailable';
        output_with_http_headers(
            $input, undef, to_json( { error => $error, error_code => $error_code } ), 'json',
            $status
        );
        exit;
    };
    @disclosure_patron_ids = ($resolved_id);
    $borrowernumber        = $resolved_id;
} else {
    $borrowernumber = $input->param('borrowernumber');
}

my $sorting_column = $input->param('iSortCol_0') || q{};
$sorting_column =
    ( $sorting_column && $sort_columns[$sorting_column] )
    ? $sort_columns[$sorting_column]
    : 'created_on';

my $sorting_direction = $input->param('sSortDir_0') || q{};
$sorting_direction = $sorting_direction eq 'asc' ? 'asc' : 'desc';

$results_per_page = undef if ( $results_per_page == -1 );

binmode STDOUT, ":encoding(UTF-8)";

my %resolver_patron_ids;

my $sql = qq{
    SELECT
        return_claims.*,

        biblio.biblionumber,
        biblio.title,
        biblio.subtitle,
        biblio.author,

        items.enumchron,
        items.barcode,
        items.itemlost
    FROM return_claims
        LEFT JOIN items USING ( itemnumber )
        LEFT JOIN biblio USING ( biblionumber )
        LEFT JOIN biblioitems USING ( biblionumber )
    WHERE return_claims.borrowernumber = ?
    ORDER BY $sorting_column $sorting_direction
};

my $sth;
if ( !$disclosure_enabled || @disclosure_patron_ids ) {
    my $dbh = C4::Context->dbh();
    $sth = $dbh->prepare($sql);
    $sth->execute($borrowernumber);
}

my $resolved   = 0;
my $unresolved = 0;
my @return_claims;
while ( $sth && ( my $claim = $sth->fetchrow_hashref() ) ) {
    $claim->{created_on_formatted} = output_pref( { dt => dt_from_string( $claim->{created_on} ) } )
        if $claim->{created_on};
    $claim->{updated_on_formatted} = output_pref( { dt => dt_from_string( $claim->{updated_on} ) } )
        if $claim->{updated_on};
    $claim->{resolved_on_formatted} = output_pref( { dt => dt_from_string( $claim->{resolved_on} ) } )
        if $claim->{resolved_on};

    my $patron = $claim->{resolved_by} ? Koha::Patrons->find( $claim->{resolved_by} ) : undef;
    if ($patron) {
        $claim->{resolved_by_data} = {
            borrowernumber => $patron->borrowernumber,
            firstname      => $patron->firstname,
            surname        => $patron->surname,
        };
        $resolver_patron_ids{ $patron->borrowernumber } = 1 if $disclosure_enabled;
    }

    my $resolution = $claim->{resolution}
        ? Koha::AuthorisedValues->find(
        {
            category         => 'RETURN_CLAIM_RESOLUTION',
            authorised_value => $claim->{resolution},
        }
        )
        : undef;
    $claim->{resolution_data} = $resolution->unblessed if $resolution;

    $claim->{resolved_on} ? $resolved++ : $unresolved++;

    push( @return_claims, $claim );
}

my $data = {
    iTotalRecords        => scalar @return_claims,
    iTotalDisplayRecords => scalar @return_claims,
    sEcho                => $input->param('sEcho') || undef,
    aaData               => \@return_claims,
    resolved             => $resolved,
    unresolved           => $unresolved
};

my $extra_options;
if ( $disclosure_enabled && @disclosure_patron_ids ) {
    my @subjects = (
        {
            patron_id    => $disclosure_patron_ids[0],
            data_classes => [qw( identity service_activity )],
        },
        map {
            {
                patron_id    => $_,
                data_classes => ['identity'],
            }
        } sort { $a <=> $b } keys %resolver_patron_ids
    );
    $extra_options = {
        patron_disclosure => {
            surface  => 'patrons.return_claims.list',
            subjects => \@subjects,
        }
    };
}

output_with_http_headers( $input, undef, to_json($data), 'json', undef, $extra_options );
